name: docs-site Vercel Preview Deployment

permissions:
  contents: write
  pull-requests: write
  issues: write
  deployments: write

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  PREVIEW_PREFIX: ngrok-docs-pr

jobs:
  check-deploy-needed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessary so we have commit history to compare to

      - name: Check for changes in docs-site
        id: changedAction
        uses: dorny/paths-filter@v3
        with:
          filters: |
            docs-site:
              - '**'

      - name: Determine if we should deploy
        id: shouldDeploy
        env:
          CHANGED: ${{ steps.changedAction.outputs.docs-site }}
        run: |
          if [ "$CHANGED" = "true" ]; then
            echo "docs-site changed - deploying Vercel preview"
            echo "should_deploy=true" >> "$GITHUB_OUTPUT"
          else
            echo "docs-site did not change - skipping Vercel preview"
            echo "should_deploy=false" >> "$GITHUB_OUTPUT"
          fi
    # pass along to the next job
    outputs:
      should_deploy: ${{ steps.shouldDeploy.outputs.should_deploy }}

  deploy-preview:
    needs: check-deploy-needed
    runs-on: ubuntu-latest
    if: needs.check-deploy-needed.outputs.should_deploy == 'true'
    steps:
      - uses: actions/checkout@v4

      # ➕ Set short 7-character commit SHA
      - name: Set short commit SHA
        run: |
          echo "SHORT_SHA=$(git rev-parse --short "${{ github.event.pull_request.head.sha }}")" >> $GITHUB_ENV

      - name: Install pnpm 📦
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      # Deploy using Vercel, but disable its built-in PR comment
      - name: Deploy to Vercel (no comment)
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_DOCS }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

          github-comment: false             # 🧼 disables default comment with raw vercel.app domain
          github-deployment: true
          alias-domains: ${{ env.PREVIEW_PREFIX }}-${{ github.event.pull_request.number }}.ngrok-dev.vercel.app
          scope: ${{ secrets.VERCEL_SCOPE }}  # optional if using a team
          working-directory: ./

      # Find previous comment (if exists) to update rather than duplicate
      - name: Find existing alias comment
        id: find-comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '🚀 **`docs-site` App Preview Deployment**'

      # Post or update a clean comment with just the alias domain
      - name: Comment on PR with alias URL only
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🚀 **`docs-site` App Preview Deployment**

            ✅ Preview URL: https://${{ env.PREVIEW_PREFIX }}-${{ github.event.pull_request.number }}.ngrok-dev.vercel.app

            🔨 Built from commit `${{ env.SHORT_SHA }}`.
          edit-mode: replace
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
