name: docs-site Vercel Production Deployment

permissions:
  contents: write
  pull-requests: write
  issues: write
  deployments: write

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_DOCS }}
  DO_NOT_TRACK: 1
  TURBO_TELEMETRY_DISABLED: 1
  VERCEL_TELEMETRY_DISABLED: 1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  www-ngrok-Vercel-PRODUCTION-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm 📦
        uses: pnpm/action-setup@v4
        # use version from package.json#packageManager field
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install Vercel CLI
        run: pnpm install --global vercel@canary

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
